# For now we have one monolithic playlist. Eventually, we break this up into
# modules or a way that makes sense. But this greatly simplifies initial
# machine setup.
---
- hosts: workstation
  tasks:
    - git: repo=git@github.com:grepory/.home.git dest=~/.home update=yes
    - command: ~/.home/bin/setup-shell
    - command: brew tap phinze/homebrew-cask
    - name: Install tools with Homebrew
      homebrew: name={{ item }} state=latest
      with_items:
        - brew-cask
        - git
        - rbenv
        - ruby-build
        - boot2docker
        - wget
    - name: Install homebrew casks
      homebrew_cask: name={{ item }} state=installed
      with_items:
        - java
        - virtualbox
        - vagrant
        - spotify
        - rubymine
        - iterm2
    - name: Write iterm2 settings
      command: {{ item }}
      with_items:
        - defaults write com.googlecode.iterm2 PromptOnQuit -bool FALSE
        - /usr/libexec/PlistBuddy -c "Set :LeftOption:2" /Users/{{ ansible_user_id }}/Library/Preferences/com.googlecode.iterm2.plist
    # Until boot2docker gets updated from upstream, the ssh-keygen has to be
    # done manually.
    - command: ssh-keygen -i ~/.ssh/id_boot2docker -t rsa -b 4096 -N ''
    - name: Setup boot2docker
      command: {{ item }}
      with_items:
        # Verbose, because just in case it fails.
        - boot2docker -v download
        - boot2docker -v init
